version: "3"

services:
  db:
    image: mongo
    container_name: "mongodb"
    volumes:
      - data-volume:/data/db
    network_mode: host
    command: mongod --smallfiles
  api:
    build: ./api
    container_name: "nodejs"
    network_mode: host
    depends_on:
      - db
    volumes:
      - ./utils/:/utils/
      - ./api/src:/opt/app/src
  web:
    build: ./forum-roleplay-ui
    container_name: "angular"
    network_mode: host

volumes:
  data-volume: